Marta develop
Bubbleheads/Buy-Cook pull request #4
Opened 2017-04-07 14:38 UTC by MartaLiutyk

On click on Categorie we have  a list of pecipes of this categorie

2017-04-07 14:57 UTC, Pastornak commented on app/src/main/java/bubbleheads/buy_cook/CategoriesAdapter.java
> - */
That shouldn`t be here

2017-04-07 14:57 UTC, Pastornak commented on app/src/main/java/bubbleheads/buy_cook/CategoriesAdapter.java
> +import org.w3c.dom.Text;
What an import is this?

2017-04-07 14:57 UTC, Pastornak commented on app/src/main/res/layout/categories_cell.xml
No empty line there (or add at the end of TextView)

2017-04-07 14:57 UTC, Pastornak commented on app/src/main/java/bubbleheads/buy_cook/CategoriesAdapter.java
> +        private final RecyclerView rv;
Do you really need this field?

2017-04-07 14:57 UTC, Pastornak commented on app/src/main/java/bubbleheads/buy_cook/CategoriesFragment.java
>      private RecyclerView recyclerView;
Can be transformed into local variable

2017-04-07 14:57 UTC, Pastornak commented on app/src/main/java/bubbleheads/buy_cook/CategoriesFragment.java
Empty line

2017-04-07 14:57 UTC, Pastornak commented on app/src/main/java/bubbleheads/buy_cook/RecipesBookAdapter.java
>      private RecipesBookAdapter.ValueFilter valueFilter;
Final fields go first

2017-04-07 14:57 UTC, Pastornak commented on app/src/main/java/bubbleheads/buy_cook/RecipesBookFragment.java
> +    private Category chosenCategory = null;
Some fields can be transfered to local final variables

2017-04-07 14:57 UTC, Pastornak commented on app/src/main/res/layout/categories_fragment.xml
Empty line (or add at the end of RecycleView)

2017-04-07 15:00 UTC, MartaLiutyk commented on app/src/main/java/bubbleheads/buy_cook/CategoriesAdapter.java
> - */
it is already deleted (red , OK ?)

2017-04-07 15:00 UTC, MartaLiutyk commented on app/src/main/java/bubbleheads/buy_cook/CategoriesAdapter.java
> +        private final RecyclerView rv;
yes.

2017-04-07 15:00 UTC, MartaLiutyk commented on app/src/main/java/bubbleheads/buy_cook/CategoriesFragment.java
it`s red. DELETED

2017-04-07 15:01 UTC, Pastornak commented on app/src/main/java/bubbleheads/buy_cook/CategoriesFragment.java
It`s not red. It`s white.

2017-04-10 16:35 UTC, ovovchak requested changes

2017-04-10 16:35 UTC, ovovchak commented on app/src/main/java/bubbleheads/buy_cook/CategoriesAdapter.java
> +                Toast.makeText(view.getContext(), Category.values()[position].getName(), Toast.LENGTH_SHORT).show();
isn't this line too long?

2017-04-10 16:35 UTC, ovovchak commented on app/src/main/java/bubbleheads/buy_cook/CategoriesAdapter.java
> +                Toast.makeText(view.getContext(), Category.values()[position].getName(), Toast.LENGTH_SHORT).show();
inside this method you twice use Category.values()[position] - this is called code duplication. Extract this as local varibal final Category category =  Category.values()[position]

2017-04-10 16:35 UTC, ovovchak commented on app/src/main/java/bubbleheads/buy_cook/CategoriesFragment.java
> +        RecyclerView recyclerView = (RecyclerView) view.findViewById(R.id.recycler_view);
final?

2017-04-10 16:35 UTC, ovovchak commented on app/src/main/java/bubbleheads/buy_cook/RecipesBookAdapter.java
>      private final ArrayList<Recipe> backupRecipes;
final fields should be close to final and not final to not final

2017-04-10 16:35 UTC, ovovchak commented on app/src/main/java/bubbleheads/buy_cook/RecipesBookFragment.java
> +        SearchView findRecipe = (SearchView) view.findViewById(R.id.searchRecipe);
final?

2017-04-10 16:35 UTC, ovovchak commented on app/src/main/java/bubbleheads/buy_cook/RecipesBookFragment.java
> +        GridView collectionView = (GridView) view.findViewById(R.id.collection_view);
final ?

2017-04-10 18:12 UTC, merged